program_options:
  tray: false              # Show tray icon
  notify: true           # Enable notifications
  automount: true        # Enable automatic mounting
  file_manager: xdg-open # Program to open mounted directories

#device_config:
  ## Example: Special options for specific devices
  #- id_uuid: "your-device-uuid"
    #options: [noexec, nodev]
    #ignore: false
    #automount: false

notifications:
  timeout: 10           # Notification timeout in seconds
  device_mounted: 20      # Show mount notifications for 5 seconds

  notification_actions:
    device_mounted:   [browse]
